modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"

[[mods]] #mandatory
modId="immersive_cooking" #mandatory
version="${version_mc}-${mod_version}" #mandatory
displayName="Immersive Cooking" #mandatory

#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional

logoFile="examplemod.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
This is a long form description of the mod. You can write whatever you want here

Have some lorem ipsum.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed mollis lacinia magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed sagittis luctus odio eu tempus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque volutpat ligula eget lacus auctor sagittis. In hac habitasse platea dictumst. Nunc gravida elit vitae sem vehicula efficitur. Donec mattis ipsum et arcu lobortis, eleifend sagittis sem rutrum. Cras pharetra quam eget posuere fermentum. Sed id tincidunt justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
'''

[[mods]]
modId = "immersive_cooking"
version = "${mod_version}"
displayName = "Immersive Cooking"
description = "A Food based mod focused on realism."
authors = "Crimson Twilight"
updateJSONURL = ""
displayURL = "https://minecraft.curseforge.com/projects/immersive-cooking/"
logoFile = "logo.png"
credits = "All the great other Git Contributors, and the nerds on IRC!"

[[dependencies.immersive_cooking]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.immersive_cooking]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2]"
ordering="NONE"
side="BOTH"

