modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
# logoFile="examplemod.png"

# --- Dependencies ---

# Minecraft Dependency
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

# NeoForge Dependency
[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)" # Set explicitly to match your neo_version
ordering="NONE"
side="BOTH"

 [[dependencies.${mod_id}]]
 modId="farmersdelight"
 type="required"
 versionRange="[${farmers_delight_version},)"
 ordering="AFTER"
 side="BOTH"